data:
  categorical_features:
    - Gender
    - Smoke
    - Diabetes
    - Favorite color
  columns_to_drop:
    - ID
  input_file: data/data.csv
  numerical_features:
    - Age
    - Ejection Fraction
    - Sodium
    - Creatinine
    - Platelets
    - Creatine phosphokinase
    - Blood Pressure
    - Hemoglobin
    - Height
    - Weight
  random_state: 42
  target_column: Survive
  test_size: 0.2
evaluation:
  cv_folds: 5
  metrics:
    - accuracy
    - precision
    - recall
    - f1
    - roc_auc
  scoring: accuracy
models:
  logistic_regression:
    C: 1.0
    max_iter: 1000
    penalty: l2
    random_state: 42
    solver: liblinear
  random_forest:
    max_depth: 10
    min_samples_leaf: 1
    min_samples_split: 2
    n_estimators: 100
    random_state: 42
output:
  metrics_dir: metrics
  models_dir: models
  plots_dir: plots
  results_dir: results
preprocessing:
  categorical:
    encoder: onehot
    strategy: constant
    fill_value: missing
  numerical:
    scaler: standard
    strategy: median
